const types = @import("../core/types.zig");
const color = @import("color.zig");
const filters = @import("filters.zig");
const transforms = @import("transforms.zig");
const std = @import("std");

// All image modifier definitions
pub const modifiers = [_]types.Argument{
    .{
        .names = .{ .single = "invert" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{},
        .description = "Invert the colors of the current image",
        .usage = "invert",
        .func = color.invertColors,
    },
    .{
        .names = .{ .single = "resize" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{ u16, u16 },
        .description = "Resize the image using nearest-neighbor sampling",
        .usage = "resize <width> <height>",
        .func = transforms.resizeImage,
    },
    .{
        .names = .{ .single = "crop" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{ u16, u16, u16, u16 },
        .description = "Crop the image using top-left coordinate and size",
        .usage = "crop <x> <y> <width> <height>",
        .func = transforms.cropImage,
    },
    .{
        .names = .{ .single = "rotate" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{f64},
        .description = "Rotate the image clockwise by any angle (auto-resizes canvas)",
        .usage = "rotate <degrees>",
        .func = transforms.rotateImage,
    },
    .{
        .names = .{ .single = "round-corners" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{u16},
        .description = "Round the corners of the image with a specified radius",
        .usage = "round-corners <radius>",
        .func = transforms.roundCornersImage,
    },
    .{
        .names = .{ .single = "flip" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{[]const u8},
        .description = "Flip the image horizontally or vertically",
        .usage = "flip <horizontal|vertical>",
        .func = transforms.flipImage,
    },
    .{
        .names = .{ .single = "grayscale" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{},
        .description = "Convert the image to grayscale",
        .usage = "grayscale",
        .func = color.grayscaleImage,
    },
    .{
        .names = .{ .single = "brightness" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{i8},
        .description = "Adjust image brightness",
        .usage = "brightness <value (-128 to 127)>",
        .func = color.adjustBrightness,
    },
    .{
        .names = .{ .single = "blur" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{u8},
        .description = "Apply a simple box blur",
        .usage = "blur <kernel_size (odd)>",
        .func = filters.blurImage,
    },
    .{
        .names = .{ .single = "saturation" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{f32},
        .description = "Adjust color saturation",
        .usage = "saturation <factor>",
        .func = color.adjustSaturation,
    },
    .{
        .names = .{ .single = "contrast" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{f32},
        .description = "Adjust image contrast",
        .usage = "contrast <factor>",
        .func = color.adjustContrast,
    },
    .{
        .names = .{ .single = "gamma" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{f32},
        .description = "Apply gamma correction",
        .usage = "gamma <value>",
        .func = color.adjustGamma,
    },
    .{
        .names = .{ .single = "sepia" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{},
        .description = "Apply sepia tone effect",
        .usage = "sepia",
        .func = color.applySepia,
    },
    .{
        .names = .{ .single = "sharpen" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{},
        .description = "Sharpen the image",
        .usage = "sharpen",
        .func = filters.sharpenImage,
    },
    .{
        .names = .{ .single = "gaussian-blur" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{f32},
        .description = "Apply Gaussian blur with configurable sigma",
        .usage = "gaussian-blur <sigma>",
        .func = filters.gaussianBlurImage,
    },
    .{
        .names = .{ .single = "emboss" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{f32},
        .description = "Apply emboss effect for 3D-like appearance",
        .usage = "emboss <strength>",
        .func = filters.embossImage,
    },
    .{
        .names = .{ .single = "color-emboss" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{f32},
        .description = "Apply emboss effect with color preservation",
        .usage = "color-emboss <strength>",
        .func = filters.colorEmbossImage,
    },
    .{
        .names = .{ .single = "vignette" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{f32},
        .description = "Apply vignette effect to darken image corners",
        .usage = "vignette <intensity (0.0-1.0)>",
        .func = filters.vignetteImage,
    },
    .{
        .names = .{ .single = "glow" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{ f32, u8 },
        .description = "Add a soft glow effect around bright areas",
        .usage = "glow <intensity (0.0-1.0)> <radius (1-20)>",
        .func = filters.glowImage,
    },
    .{
        .names = .{ .single = "posterize" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{u8},
        .description = "Reduce color levels for artistic poster effect",
        .usage = "posterize <levels (2-256)>",
        .func = color.posterizeImage,
    },
    .{
        .names = .{ .single = "hue-shift" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{f32},
        .description = "Shift the hue of all colors in the image",
        .usage = "hue-shift <degrees (-180 to 180)>",
        .func = color.hueShiftImage,
    },
    .{
        .names = .{ .single = "adjust-hsl" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{ f32, f32, f32 },
        .description = "Adjust hue, saturation, and lightness separately",
        .usage = "adjust-hsl <hue_shift> <saturation_factor> <lightness_factor>",
        .func = color.adjustHSL,
    },
    .{
        .names = .{ .single = "median-filter" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{u8},
        .description = "Apply median filter for noise reduction",
        .usage = "median-filter <kernel_size (odd)>",
        .func = filters.medianFilterImage,
    },
    .{
        .names = .{ .single = "threshold" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{u8},
        .description = "Convert image to pure black and white based on luminance threshold",
        .usage = "threshold <value (0-255)>",
        .func = color.thresholdImage,
    },
    .{
        .names = .{ .single = "solarize" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{u8},
        .description = "Invert colors above threshold for artistic effect",
        .usage = "solarize <threshold (0-255)>",
        .func = color.solarizeImage,
    },
    .{
        .names = .{ .single = "edge-detect" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{},
        .description = "Detect edges using Sobel operator",
        .usage = "edge-detect",
        .func = filters.edgeDetectImage,
    },
    .{
        .names = .{ .single = "pixelate" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{u8},
        .description = "Apply pixelation/mosaic effect",
        .usage = "pixelate <block_size>",
        .func = filters.pixelateImage,
    },
    .{
        .names = .{ .single = "noise" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{f32},
        .description = "Add random noise to image",
        .usage = "noise <amount (0.0-1.0)>",
        .func = filters.addNoiseImage,
    },
    .{
        .names = .{ .single = "denoise" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{u8},
        .description = "Remove noise from image using bilateral filter",
        .usage = "denoise <strength (1-10)>",
        .func = filters.denoiseImage,
    },
    .{
        .names = .{ .single = "exposure" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{f32},
        .description = "Adjust exposure (like camera EV)",
        .usage = "exposure <value (-2.0 to 2.0)>",
        .func = color.adjustExposure,
    },
    .{
        .names = .{ .single = "vibrance" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{f32},
        .description = "Adjust vibrance (smart saturation)",
        .usage = "vibrance <factor>",
        .func = color.adjustVibrance,
    },
    .{
        .names = .{ .single = "equalize" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{},
        .description = "Apply histogram equalization for better contrast",
        .usage = "equalize",
        .func = color.equalizeImage,
    },
    .{
        .names = .{ .single = "equalize-area" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{ u16, u16, u16, u16 },
        .description = "Apply histogram equalization to a specific region",
        .usage = "equalize-area <x> <y> <width> <height>",
        .func = color.equalizeAreaImage,
    },
    .{
        .names = .{ .single = "colorize" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{ u8, u8, u8, f32 },
        .description = "Colorize/tint image with RGB color",
        .usage = "colorize <r> <g> <b> <intensity (0.0-1.0)>",
        .func = color.colorizeImage,
    },
    .{
        .names = .{ .single = "adjust-channels" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{ f32, f32, f32 },
        .description = "Adjust the intensity of individual RGB color channels",
        .usage = "adjust-channels <red_mult> <green_mult> <blue_mult>",
        .func = color.adjustChannels,
    },
    .{
        .names = .{ .single = "duotone" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{ u8, u8, u8, u8, u8, u8 },
        .description = "Apply duotone effect (Spotify-style)",
        .usage = "duotone <dark_r> <dark_g> <dark_b> <light_r> <light_g> <light_b>",
        .func = color.duotoneImage,
    },
    .{
        .names = .{ .single = "oil-painting" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{usize},
        .description = "Apply oil painting artistic effect",
        .usage = "oil-painting <radius>",
        .func = filters.oilPaintingImage,
    },
    .{
        .names = .{ .single = "tilt-shift" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{ f32, f32, f32 },
        .description = "Advanced tilt-shift effect with two-pass Gaussian blur and smooth focus transitions for realistic miniature appearance",
        .usage = "tilt-shift <blur_strength> <focus_position> <focus_width>",
        .func = filters.tiltShiftImage,
    },
    .{
        .names = .{ .single = "edge-enhancement" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{f32},
        .description = "Enhance edges by combining edge detection with original image",
        .usage = "edge-enhancement <strength (0.0-2.0)>",
        .func = filters.edgeEnhancementImage,
    },
    .{
        .names = .{ .single = "gradient-linear" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{ []const u8, []const u8, f32, f32 },
        .description = "Apply linear gradient overlay",
        .usage = "gradient-linear <start_color> <end_color> <angle> <opacity>",
        .func = filters.gradientLinearImage,
    },
    .{
        .names = .{ .single = "gradient-radial" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{ f32, f32, []const u8, []const u8, f32, f32 },
        .description = "Apply radial gradient overlay",
        .usage = "gradient-radial <center_x> <center_y> <start_color> <end_color> <radius> <opacity>",
        .func = filters.gradientRadialImage,
    },
    .{
        .names = .{ .single = "censor" },
        .option_type = types.ArgType.Modifier,
        .param_types = &[_]type{ f32, f32, f32, f32, []const u8, usize },
        .description = "Apply censoring effect (blur/pixelate/black) to a region",
        .usage = "censor <x> <y> <width> <height> <method> <strength>",
        .func = filters.censorImage,
    },
};
