name: Build Gallery

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
permissions:
  contents: write
  
jobs:
  build-gallery:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # Fetch full history for proper git operations
        fetch-depth: 0
        
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.15.1
        
    - name: Build gallery
      run: zig build gallery
      
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain examples/gallery/)" ]; then
          echo "gallery_changed=true" >> $GITHUB_OUTPUT
        else
          echo "gallery_changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit gallery updates
      if: steps.verify-changed-files.outputs.gallery_changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add examples/gallery/
        git commit -m "Update gallery examples [CI]"
        git push