name: Development Build

on:
  push:
    branches: ["*"]

jobs:
  build:
    name: Build on multiple targets
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        TARGET:
          [
            x86_64-linux,
            x86_64-macos,
            x86_64-windows,
          ]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set the release version
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV

      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.1

      - name: Cache Zig dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/zig
          key: ${{ runner.os }}-zig-${{ hashFiles('**/build.zig.zon') }}
          restore-keys: |
            ${{ runner.os }}-zig-

      - name: Build
        run: zig build -Dtarget=${{ matrix.TARGET }} -Doptimize=ReleaseSafe --summary all

      - name: Run tests
        if: matrix.TARGET == 'x86_64-linux'
        run: zig build test -Dtarget=${{ matrix.TARGET }} -Dtests